name: Update rulesets
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update rulesets
      run: python update_rulesets.py
    - name: Commit rulesets
      run: |
        git config --global user.name 'Koodous'
        git config --global user.email 'koodous@koodous.com'
        git add --all
        git commit -am "Updated rulesets at "`date --iso-8601`
        git push
